#!/usr/bin/env bash
# performing a 301 moved permanently

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="s/server _;\n\trewrite ^\//redirect_me https:\/\/github.com/SarahEmmy permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
