#!/usr/bin/env bash

# configuring web-01 to have an HTTP response header

# Update and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a simple index.html file
echo "Hello, World!" | sudo tee /var/www/html/index.html

# Performing a redirection 
new_string="server_name -;\n\trewrite ^\/redirect_me https:\/\/github.com\/SarahEmmy permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Create a custom error 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# customHTTP response header
sudo sed -i "server_name _;/a add_header X-served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#Testing for syntax errors
sudo nginx -t 

# Start the Nginx service
sudo service nginx start
