#!/usr/bin/env bash

# Get the hostname
var=$(hostname)

# Define new strings for Nginx configuration
new_string="error_page 404 /custom_404.html;\n location /redirect_me {\n return 301 \$scheme://www.google.com;"
new_string2="server {\n\tadd_header X-Served-By $var;"

# Update and install Nginx
apt-get update -y
apt-get install nginx -y

# Create a simple index.html file
echo "Hello, World!" > /usr/share/nginx/html/index.html

# Create a directory for custom content
mkdir -p /var/www/html

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Update the Nginx configuration with the custom strings
sudo sed -i -E "s/^[^#]+location \/ {/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server {/$new_string2/" /etc/nginx/sites-available/default

# Start the Nginx service
sudo service nginx start
